#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from libparam.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */

#define yyparse libparamparse
#define yylex libparamlex
#define yyerror libparamerror
#define yylval libparamlval
#define yychar libparamchar
#define yydebug libparamdebug

#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 32 "libparam.y"

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <libddbg/libddbg.h>
#include "libparam.h"

#define YYERROR_VERBOSE

void yyerror (char *s) {
  fprintf(stderr, "*** error: on line %d of %s: ", lp_lineno, lp_filename);
  fprintf(stderr, "%s\n", s);
}


#line 55 "libparam.y"
typedef union {
  double d;
  int i;
  char *s;

  struct lp_block *b;
  struct { struct lp_block **b; int blen; } blocks;

  struct lp_param *p;
  struct { struct lp_param **p; int plen; } params;

  struct lp_list *l;

  struct lp_value *v;

  struct { struct lp_topospec *l; int len; } topo;
  struct lp_inst *inst;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#define YY_parse_PARSE libparamparse
#define YY_parse_LEX libparamlex
#define YY_parse_ERROR libparamerror
#define YY_parse_LVAL libparamlval
#define YY_parse_CHAR libparamchar
#define YY_parse_DEBUG libparamdebug

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	LBRACE	258
#define	RBRACE	259
#define	SEMI	260
#define	EQUAL	261
#define	TRUE	262
#define	FALSE	263
#define	DECINT	264
#define	HEXINT	265
#define	FLOAT	266
#define	STRING	267
#define	LBRAK	268
#define	RBRAK	269
#define	COMMA	270
#define	QU	271
#define	COLON	272
#define	NEWLINE	273
#define	SOURCE	274
#define	DOTDOT	275
#define	AS	276
#define	INSTANTIATE	277
#define	TOPOLOGY	278


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int LBRACE;
static const int RBRACE;
static const int SEMI;
static const int EQUAL;
static const int TRUE;
static const int FALSE;
static const int DECINT;
static const int HEXINT;
static const int FLOAT;
static const int STRING;
static const int LBRAK;
static const int RBRAK;
static const int COMMA;
static const int QU;
static const int COLON;
static const int NEWLINE;
static const int SOURCE;
static const int DOTDOT;
static const int AS;
static const int INSTANTIATE;
static const int TOPOLOGY;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,LBRACE=258
	,RBRACE=259
	,SEMI=260
	,EQUAL=261
	,TRUE=262
	,FALSE=263
	,DECINT=264
	,HEXINT=265
	,FLOAT=266
	,STRING=267
	,LBRAK=268
	,RBRAK=269
	,COMMA=270
	,QU=271
	,COLON=272
	,NEWLINE=273
	,SOURCE=274
	,DOTDOT=275
	,AS=276
	,INSTANTIATE=277
	,TOPOLOGY=278


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::LBRACE=258;
const int YY_parse_CLASS::RBRACE=259;
const int YY_parse_CLASS::SEMI=260;
const int YY_parse_CLASS::EQUAL=261;
const int YY_parse_CLASS::TRUE=262;
const int YY_parse_CLASS::FALSE=263;
const int YY_parse_CLASS::DECINT=264;
const int YY_parse_CLASS::HEXINT=265;
const int YY_parse_CLASS::FLOAT=266;
const int YY_parse_CLASS::STRING=267;
const int YY_parse_CLASS::LBRAK=268;
const int YY_parse_CLASS::RBRAK=269;
const int YY_parse_CLASS::COMMA=270;
const int YY_parse_CLASS::QU=271;
const int YY_parse_CLASS::COLON=272;
const int YY_parse_CLASS::NEWLINE=273;
const int YY_parse_CLASS::SOURCE=274;
const int YY_parse_CLASS::DOTDOT=275;
const int YY_parse_CLASS::AS=276;
const int YY_parse_CLASS::INSTANTIATE=277;
const int YY_parse_CLASS::TOPOLOGY=278;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		58
#define	YYFLAG		-32768
#define	YYNTBASE	24

#define YYTRANSLATE(x) ((unsigned)(x) <= 278 ? yytranslate[x] : 36)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     1,     5,     8,    11,    16,    20,    26,    31,    32,
    34,    38,    44,    48,    52,    54,    56,    60,    61,    63,
    67,    73,    77,    79,    81,    83,    85,    87,    89,    91,
    93
};

static const short yyrhs[] = {    -1,
    24,    23,    26,     0,    24,    27,     0,    24,    25,     0,
    22,    32,    21,    12,     0,    12,    12,    32,     0,    12,
    12,     3,    29,     4,     0,    12,     3,    29,     4,     0,
     0,    30,     0,    32,     6,    34,     0,    29,    15,    32,
     6,    34,     0,    29,    15,    30,     0,    35,     6,    34,
     0,     9,     0,    10,     0,    13,    33,    14,     0,     0,
    34,     0,    12,    20,    12,     0,    33,    15,    12,    20,
    12,     0,    33,    15,    34,     0,    31,     0,    11,     0,
    12,     0,    32,     0,    28,     0,    27,     0,    26,     0,
    12,     0,    35,    12,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    92,    93,    99,   106,   117,   124,   153,   190,   211,   212,
   219,   239,   253,   264,   278,   279,   283,   289,   295,   305,
   345,   381,   388,   391,   396,   400,   404,   409,   415,   428,
   434
};

static const char * const yytname[] = {   "$","error","$illegal.","LBRACE","RBRACE",
"SEMI","EQUAL","TRUE","FALSE","DECINT","HEXINT","FLOAT","STRING","LBRAK","RBRAK",
"COMMA","QU","COLON","NEWLINE","SOURCE","DOTDOT","AS","INSTANTIATE","TOPOLOGY",
"BLOCKS","INST","TOPOSPEC","BLOCKDEF","BLOCKVAL","EXPS","EXP","NUM","LIST","LITEMS",
"VALUE","PARAM",""
};
#endif

static const short yyr1[] = {     0,
    24,    24,    24,    24,    25,    26,    27,    28,    29,    29,
    29,    29,    29,    30,    31,    31,    32,    33,    33,    33,
    33,    33,    34,    34,    34,    34,    34,    34,    34,    35,
    35
};

static const short yyr2[] = {     0,
     0,     3,     2,     2,     4,     3,     5,     4,     0,     1,
     3,     5,     3,     3,     1,     1,     3,     0,     1,     3,
     5,     3,     1,     1,     1,     1,     1,     1,     1,     1,
     2
};

static const short yydefact[] = {     1,
     0,     0,     0,     0,     4,     3,     0,    18,     0,     0,
     2,     9,    15,    16,    24,    25,    29,    28,    27,    23,
    26,     0,    19,     0,     0,    30,     0,    10,     0,     0,
     9,     0,     0,    17,     0,     5,     6,     7,     0,     0,
     0,    31,     0,    20,    25,    22,    13,     0,    25,    11,
    14,     8,     0,     0,    21,    12,     0,     0
};

static const short yydefgoto[] = {     1,
     5,    17,    18,    19,    27,    28,    20,    21,    22,    23,
    30
};

static const short yypact[] = {-32768,
     1,    -8,     5,     3,-32768,-32768,    47,    22,    32,    42,
-32768,    25,-32768,-32768,-32768,     0,-32768,-32768,-32768,-32768,
-32768,    37,-32768,    43,     5,-32768,     2,-32768,    50,    -1,
    25,    13,    45,-32768,    31,-32768,-32768,-32768,    25,    36,
    36,-32768,    10,-32768,     7,-32768,-32768,    52,    27,-32768,
-32768,-32768,    48,    36,-32768,-32768,    59,-32768
};

static const short yypgoto[] = {-32768,
-32768,    57,    61,-32768,    33,    24,-32768,    -3,-32768,   -33,
-32768
};


#define	YYLAST		64


static const short yytable[] = {     9,
    57,    46,    31,     7,    41,    38,    50,    51,    29,    31,
    42,    32,     2,    52,    10,    12,    39,     8,    32,    33,
    56,    37,     3,     4,    39,     8,    53,    29,    37,    31,
    13,    14,    15,    16,     8,    48,    26,     8,    32,    13,
    14,    15,    45,     8,    13,    14,    15,    49,     8,    12,
    34,    35,    24,    25,    36,    40,    44,    54,    58,    55,
    11,     6,    47,    43
};

static const short yycheck[] = {     3,
     0,    35,     3,    12,     6,     4,    40,    41,    12,     3,
    12,    12,    12,     4,    12,     3,    15,    13,    12,    20,
    54,    25,    22,    23,    15,    13,    20,    31,    32,     3,
     9,    10,    11,    12,    13,    39,    12,    13,    12,     9,
    10,    11,    12,    13,     9,    10,    11,    12,    13,     3,
    14,    15,    21,    12,    12,     6,    12,     6,     0,    12,
     4,     1,    39,    31
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 92 "libparam.y"
{ ;
    break;}
case 2:
#line 93 "libparam.y"
{
/*      printf("blocks topospec\n"); */

  lp_new_tl_topo(yyvsp[0].topo.l, lp_filename);  
  load_topo(yyvsp[0].topo.l, yyvsp[0].topo.len);
;
    break;}
case 3:
#line 100 "libparam.y"
{ 
/*    printf("blocks blockdef\n"); */
  lp_new_tl_block(yyvsp[0].b, lp_filename);
  load_block(yyvsp[0].b); 
;
    break;}
case 4:
#line 106 "libparam.y"
{   
  lp_new_tl_inst(yyvsp[0].inst, lp_filename);
  lp_inst_list(yyvsp[0].inst);
;
    break;}
case 5:
#line 117 "libparam.y"
{
  yyval.inst = malloc(sizeof(struct lp_inst));
  yyval.inst->source_file = lp_filename;
  yyval.inst->l = yyvsp[-2].l;
  yyval.inst->name = yyvsp[0].s;
;
    break;}
case 6:
#line 124 "libparam.y"
{
/*    printf("topospec\n"); */

  yyval.topo.l = malloc(sizeof(struct lp_topospec));
  yyval.topo.l->source_file = lp_filename;
  yyval.topo.len = 1;
  yyval.topo.l[0].type = yyvsp[-2].s;
  yyval.topo.l[0].name = yyvsp[-1].s;
  yyval.topo.l[0].l = yyvsp[0].l;
;
    break;}
case 7:
#line 154 "libparam.y"
{
  struct lp_block *parent;

/*    printf("start of blockdef: %s\n", $2); */

  yyval.b = malloc(sizeof(struct lp_block));
  bzero(yyval.b, sizeof(struct lp_block));
  yyval.b->source_file = lp_filename;

  yyval.b->type = lp_mod_name(lp_lookup_base_type(yyvsp[-4].s,0));
  if(yyval.b->type == -1) {
    fprintf(stderr, "*** error: Unknown block type: %s\n", yyvsp[-4].s);
    YYABORT;
  }

  if(lp_lookup_type(yyvsp[-3].s,0)) {
    fprintf(stderr, "*** warning: ignoring redefinition of %s\n", yyvsp[-3].s);
  }
  else {
    parent = lp_lookup_spec(yyvsp[-4].s);

    yyval.b->name = yyvsp[-3].s;
    yyval.b->params = yyvsp[-1].params.p;
    yyval.b->params_len = yyvsp[-1].params.plen;
    if(lp_add_type(yyvsp[-3].s, yyvsp[-4].s)) {
      fprintf(stderr, "*** error: couldn't add type %s::%s\n", yyvsp[-4].s, yyvsp[-3].s);
    }
    
    if(parent) lp_setup_subtype(parent, yyval.b);
  }
  
  free(yyvsp[-4].s);
;
    break;}
case 8:
#line 190 "libparam.y"
{
  yyval.b = malloc(sizeof(struct lp_block));
  bzero(yyval.b, sizeof(struct lp_block));
  yyval.b->source_file = lp_filename;
  yyval.b->name = 0;
  yyval.b->params = yyvsp[-1].params.p;
  yyval.b->params_len = yyvsp[-1].params.plen;
  yyval.b->type = lp_mod_name(yyvsp[-3].s);

  if(yyval.b->type == -1) {
    fprintf(stderr, "*** error: no such module %s\n", yyvsp[-3].s);
    YYABORT;
  }

  yyval.b->loader = lp_modules[yyval.b->type]->fn;

  free(yyvsp[-3].s);
;
    break;}
case 9:
#line 211 "libparam.y"
{ yyval.params.p = 0; yyval.params.plen = 0; ;
    break;}
case 10:
#line 212 "libparam.y"
{ 
/*      printf("first exp\n");  */
  yyval.params.p = malloc(8 * sizeof(int *)); 
  bzero(yyval.params.p, 8*sizeof(int *)); 
  yyval.params.plen = 8; 
  yyval.params.p[0] = yyvsp[0].p;
;
    break;}
case 11:
#line 219 "libparam.y"
{

  int c; struct lp_param *tmp;

/*    printf("another exp\n");  */

  yyval.params.p = malloc(yyvsp[-2].l->values_len * sizeof(int *));
  yyval.params.plen = yyvsp[-2].l->values_len;
  bzero(yyval.params.p, yyvsp[-2].l->values_len * (sizeof(int *)));

  for(c = 0; c < yyvsp[-2].l->values_len; c++) {
    if(!yyvsp[-2].l->values[c]) continue;
    ddbg_assert(yyvsp[-2].l->values[c]->t == S);
    tmp = malloc(sizeof(struct lp_param));
    tmp->name = yyvsp[-2].l->values[c]->v.s;
    tmp->v = yyvsp[0].v;
    if(lp_add_param(&(yyval.params.p), &(yyval.params.plen), tmp)) YYABORT;
  }

;
    break;}
case 12:
#line 239 "libparam.y"
{
    int c; struct lp_param *tmp;

  for(c = 0; c < yyvsp[-2].l->values_len; c++) {
    if(!yyvsp[-2].l->values[c]) continue;
    ddbg_assert(yyvsp[-2].l->values[c]->t == S);
    tmp = lp_new_param(yyvsp[-2].l->values[c]->v.s, 0, yyvsp[0].v);
/* malloc(sizeof(struct lp_param)); */
/*     tmp->name =  */
/*     tmp->v = $5; */
    if(lp_add_param(&(yyvsp[-4].params.p), &(yyvsp[-4].params.plen), tmp)) YYABORT;
  }
  yyval.params = yyvsp[-4].params;
;
    break;}
case 13:
#line 254 "libparam.y"
{ 

/*    printf("nth exp.\n"); */
  if(lp_add_param(&(yyvsp[-2].params.p), &(yyvsp[-2].params.plen), yyvsp[0].p)) YYABORT;

  yyval.params = yyvsp[-2].params;
;
    break;}
case 14:
#line 264 "libparam.y"
{
    /* printf("got a param exp: %s (%s)\n", $1->name, $1->source_file); */
  
  yyval.p = yyvsp[-2].p;

/* malloc(sizeof(struct lp_param));  */
/*   $$->source_file = lp_filename; */
/*   $$->name = $1;  */
  yyval.p->v = yyvsp[0].v;  
;
    break;}
case 17:
#line 284 "libparam.y"
{
  yyval.l = yyvsp[-1].l;
;
    break;}
case 18:
#line 289 "libparam.y"
{ 
  yyval.l = lp_new_list();
  /*  bzero($$, sizeof(struct lp_list)); */
  /*  $$->values_len = 0; */
  /*  $$ */
;
    break;}
case 19:
#line 295 "libparam.y"
{
/*    printf("first list item\n"); */
  yyval.l = lp_new_list();
/*   bzero($$, sizeof(struct lp_list)); */
/*   $$->values = malloc(8 * sizeof(int *)); */
/*   bzero($$->values, 8 * sizeof(int *)); */
/*   $$->values_len = 8; */
  yyval.l->values_pop = 1; 
  yyval.l->values[0] = yyvsp[0].v; 
;
    break;}
case 20:
#line 305 "libparam.y"
{
  char *s1, *s2;
  char temp[1024];
  int i1, i2, n, c;
  if(dumb_split(yyvsp[-2].s, &s1, &i1) || dumb_split(yyvsp[0].s, &s2, &i2)) {
    fprintf(stderr, "*** error: bad lex range\n");
    YYABORT;
  }
  /* done with these */
  free(yyvsp[-2].s);
  free(yyvsp[0].s);

  if(strcmp(s1,s2)) {
    fprintf(stderr, "*** error: bad lex range\n");
    YYABORT;
  }
  n = i2 - i1 + 1;
  if(n <= 0) {
    fprintf(stderr, "*** error: bad lex range\n");
    YYABORT;
  }

  yyval.l = lp_new_list();
/*   bzero($$, sizeof(struct lp_list)); */
/*   $$->values_len = n; */
/*   $$->values = malloc(n * sizeof(int *)); */

  for(c = 0; c < n; c++) {
    struct lp_value *v;
    snprintf(temp, 1024, "%s%d", s2, c + i1);
/*     $$->values[c] = malloc(sizeof(struct lp_value)); */
/*     $$->values[c]->t = S; */
    v = lp_new_stringv(strdup(temp));
    //    $$->values[c]->v.s = strdup(temp);
    yyval.l = lp_list_add(yyval.l, v);
  }


;
    break;}
case 21:
#line 345 "libparam.y"
{
  char *s1, *s2;
  char temp[1024];
  int i1, i2, n, c;
  struct lp_value *tmp;

  if(dumb_split(yyvsp[-2].s, &s1, &i1) || dumb_split(yyvsp[0].s, &s2, &i2)) {
    fprintf(stderr, "*** error: bad lex range\n");
    YYABORT;
  }
  /* done with these */
  free(yyvsp[-2].s);
  free(yyvsp[0].s);

  if(strcmp(s1,s2)) {
    fprintf(stderr, "*** error: bad lex range\n");
    YYABORT;
  }
  n = i2 - i1 + 1;
  if(n <= 0) {
    fprintf(stderr, "*** error: bad lex range\n");
    YYABORT;
  }

  for(c = 0; c < n; c++) {
    snprintf(temp, 1024, "%s%d", s2, c + i1);
    tmp = lp_new_stringv(strdup(temp));
/*       = malloc(sizeof(struct lp_value)); */
/*     tmp->t = S; */
/*     tmp->v.s = strdup(temp); */
    yyval.l = lp_list_add(yyvsp[-4].l, tmp);
  }


;
    break;}
case 22:
#line 381 "libparam.y"
{
/*    printf("list item\n"); */
  yyval.l = lp_list_add(yyvsp[-2].l, yyvsp[0].v);
;
    break;}
case 23:
#line 388 "libparam.y"
{
  yyval.v = lp_new_intv(yyvsp[0].i);
  yyval.v->source_file = lp_filename;
;
    break;}
case 24:
#line 392 "libparam.y"
{
  yyval.v = lp_new_doublev(yyvsp[0].d);
  yyval.v->source_file = lp_filename;
;
    break;}
case 25:
#line 396 "libparam.y"
{
   yyval.v = lp_new_stringv(yyvsp[0].s);
  yyval.v->source_file = lp_filename;
;
    break;}
case 26:
#line 400 "libparam.y"
{
  yyval.v = lp_new_listv(yyvsp[0].l);
  yyval.v->source_file = lp_filename;
;
    break;}
case 27:
#line 404 "libparam.y"
{
  yyval.v = lp_new_blockv(yyvsp[0].b);
  yyval.v->source_file = lp_filename;
  yyval.v->t = BLOCK;
;
    break;}
case 28:
#line 409 "libparam.y"
{ 
  yyval.v = malloc(sizeof(struct lp_value));
  yyval.v->source_file = lp_filename;
  yyval.v->v.b = yyvsp[0].b;
  yyval.v->t = BLOCK;
;
    break;}
case 29:
#line 415 "libparam.y"
{
/*    printf("topospec value\n"); */
  yyval.v = malloc(sizeof(struct lp_value));
  yyval.v->source_file = lp_filename;
  yyval.v->v.t.l = yyvsp[0].topo.l;
  yyval.v->v.t.len = yyvsp[0].topo.len;

  yyval.v->t = TOPOSPEC;
;
    break;}
case 30:
#line 428 "libparam.y"
{
/*    printf("empty param\n");  */
  yyval.p = calloc(1, sizeof(struct lp_param));
  yyval.p->name = yyvsp[0].s;
  yyval.p->source_file = lp_filename;
;
    break;}
case 31:
#line 434 "libparam.y"
{
  char *tmp = calloc(2 * (strlen(yyvsp[-1].p->name) + strlen(yyvsp[0].s)), sizeof(*tmp)); 

  yyval.p = yyvsp[-1].p;
  strcat(tmp, yyvsp[-1].p->name);
  strcat(tmp, " ");
  strcat(tmp, yyvsp[0].s);

  free(yyval.p->name); free(yyvsp[0].s);

  yyval.p->name = tmp;  
;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 449 "libparam.y"


/*  void main(void) { */

  //  printvars();
/*    disksim =  */
/*      disksim_initialize_disksim_structure(malloc(sizeof(struct disksim)), */
/*  					 sizeof(struct disksim)); */
/*    lp_init_typetbl(); */

/*    disksim->startaddr = malloc(1<<24); */
/*    disksim->curroffset = 0; */
/*    disksim->totallength = 1<<24; */

/*    top_file = 0; */
/*    input_files[0] = disksim_param_create_buffer(stdin, 1<<14); */

/*    yyparse(); */
/*  } */








