my out:main.o fop.o rpc_fun.o fop.h rpc_c.h structer.h
	gcc main.o fop.o rpc_fun.o -o my.out
main.out:main.c
	gcc main.c -c
fop.out:fop.c
	gcc fop.c -c
rpc_fun.out:rpc_c.c
	gcc rpc_fun.c -c



