a.out : main.o astrncpy.o astrcpy.o astrcat.o astrlen.o astrncat.o  astrncmp.o astrcmp.o
	gcc main.o astrncpy.o astrcpy.o astrcat.o astrlen.o astrncat.o  astrncmp.o astrcmp.o
main.o: main.c defs.h
	gcc -c main.c
astrncpy.o: astrncpy.c
	gcc -c astrncpy.c
astrcpy.o: astrcpy.c
	gcc -c astrcpy.c
astrcat.o: astrcat.c
	gcc -c astrcat.c
astrlen.o: astrlen.c
	gcc -c astrlen.c
astrncat.o: astrncat.c
	gcc -c astrncat.c
astrcmp.o: astrcmp.c
	gcc -c astrcmp.c
astrncmp.o: astrncmp.c
	gcc -c astrncmp.c
