a.out:3-main.o astrcasecmp.o astrcat.o astrcmp.o astrcpy.o astrncmp.o astrncpy.o atolower.o atoupper.o astrlen.o astrncat.o
	gcc 3-main.o astrcasecmp.o astrcat.o astrcmp.o astrcpy.o astrncmp.o
	astrncpy.o atolower.o atoupper.o astrlen.o astrncat.o

main.o: 3-main.c
	gcc 3-main.c -c

astrcasecmp.o: astrcasecmp.c
	gcc astrcasecmp.c -c

astrcat.o:astrcat.c
	gcc astrcat.c -c

astrcmp.o:astrcmp.c
	gcc astrcmp.c -c

astrcpy.o:astrcpy.c
	gcc astrcpy.c -c

astrncmp.o:astrncmp.c
	gcc astrncmp.c -c

astrncpy.o:astrncpy.c
	gcc astrncpy.c -c

atolower.o:atolower.c
	gcc atolower.c -c

atoupper.o:atoupper.c
	gcc atoupper.c -c

astrlen.o:astrlen.c
	gcc astrlen.c -c

astrncat.o:astrncat.c
	gcc astrncat.c -c
